const fs = require('fs');

const countryCodes = {
  AF: {
    name: 'Afghanistan',
    dial_code: 93,
  },
  AL: {
    name: 'Albania',
    dial_code: 355,
  },
  DZ: {
    name: 'Algeria',
    dial_code: 213,
  },
  AS: {
    name: 'American Samoa',
    dial_code: 1,
  },
  AD: {
    name: 'Andorra',
    dial_code: 376,
  },
  AO: {
    name: 'Angola',
    dial_code: 244,
  },
  AI: {
    name: 'Anguilla',
    dial_code: 1,
  },
  AG: {
    name: 'Antigua',
    dial_code: 1,
  },
  AR: {
    name: 'Argentina',
    dial_code: 54,
  },
  AM: {
    name: 'Armenia',
    dial_code: 374,
  },
  AW: {
    name: 'Aruba',
    dial_code: 297,
  },
  AU: {
    name: 'Australia',
    dial_code: 61,
  },
  AT: {
    name: 'Austria',
    dial_code: 43,
  },
  AZ: {
    name: 'Azerbaijan',
    dial_code: 994,
  },
  BH: {
    name: 'Bahrain',
    dial_code: 973,
  },
  BD: {
    name: 'Bangladesh',
    dial_code: 880,
  },
  BB: {
    name: 'Barbados',
    dial_code: 1,
  },
  BY: {
    name: 'Belarus',
    dial_code: 375,
  },
  BE: {
    name: 'Belgium',
    dial_code: 32,
  },
  BZ: {
    name: 'Belize',
    dial_code: 501,
  },
  BJ: {
    name: 'Benin',
    dial_code: 229,
  },
  BM: {
    name: 'Bermuda',
    dial_code: 1,
  },
  BT: {
    name: 'Bhutan',
    dial_code: 975,
  },
  BO: {
    name: 'Bolivia',
    dial_code: 591,
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    dial_code: 387,
  },
  BW: {
    name: 'Botswana',
    dial_code: 267,
  },
  BR: {
    name: 'Brazil',
    dial_code: 55,
  },
  IO: {
    name: 'British Indian Ocean Territory',
    dial_code: 246,
  },
  VG: {
    name: 'British Virgin Islands',
    dial_code: 1,
  },
  BN: {
    name: 'Brunei',
    dial_code: 673,
  },
  BG: {
    name: 'Bulgaria',
    dial_code: 359,
  },
  BF: {
    name: 'Burkina Faso',
    dial_code: 226,
  },
  MM: {
    name: 'Burma Myanmar',
    dial_code: 95,
  },
  BI: {
    name: 'Burundi',
    dial_code: 257,
  },
  KH: {
    name: 'Cambodia',
    dial_code: 855,
  },
  CM: {
    name: 'Cameroon',
    dial_code: 237,
  },
  CA: {
    name: 'Canada',
    dial_code: 1,
  },
  CV: {
    name: 'Cape Verde',
    dial_code: 238,
  },
  KY: {
    name: 'Cayman Islands',
    dial_code: 1,
  },
  CF: {
    name: 'Central African Republic',
    dial_code: 236,
  },
  TD: {
    name: 'Chad',
    dial_code: 235,
  },
  CL: {
    name: 'Chile',
    dial_code: 56,
  },
  CN: {
    name: 'China',
    dial_code: 86,
  },
  CO: {
    name: 'Colombia',
    dial_code: 57,
  },
  KM: {
    name: 'Comoros',
    dial_code: 269,
  },
  CK: {
    name: 'Cook Islands',
    dial_code: 682,
  },
  CR: {
    name: 'Costa Rica',
    dial_code: 506,
  },
  CI: {
    name: "Cote d'Ivoire",
    dial_code: 225,
  },
  HR: {
    name: 'Croatia',
    dial_code: 385,
  },
  CU: {
    name: 'Cuba',
    dial_code: 53,
  },
  CY: {
    name: 'Cyprus',
    dial_code: 357,
  },
  CZ: {
    name: 'Czech Republic',
    dial_code: 420,
  },
  CD: {
    name: 'Democratic Republic of Congo',
    dial_code: 243,
  },
  DK: {
    name: 'Denmark',
    dial_code: 45,
  },
  DJ: {
    name: 'Djibouti',
    dial_code: 253,
  },
  DM: {
    name: 'Dominica',
    dial_code: 1,
  },
  DO: {
    name: 'Dominican Republic',
    dial_code: 1,
  },
  EC: {
    name: 'Ecuador',
    dial_code: 593,
  },
  EG: {
    name: 'Egypt',
    dial_code: 20,
  },
  SV: {
    name: 'El Salvador',
    dial_code: 503,
  },
  GQ: {
    name: 'Equatorial Guinea',
    dial_code: 240,
  },
  ER: {
    name: 'Eritrea',
    dial_code: 291,
  },
  EE: {
    name: 'Estonia',
    dial_code: 372,
  },
  ET: {
    name: 'Ethiopia',
    dial_code: 251,
  },
  FK: {
    name: 'Falkland Islands',
    dial_code: 500,
  },
  FO: {
    name: 'Faroe Islands',
    dial_code: 298,
  },
  FM: {
    name: 'Federated States of Micronesia',
    dial_code: 691,
  },
  FJ: {
    name: 'Fiji',
    dial_code: 679,
  },
  FI: {
    name: 'Finland',
    dial_code: 358,
  },
  FR: {
    name: 'France',
    dial_code: 33,
  },
  GF: {
    name: 'French Guiana',
    dial_code: 594,
  },
  PF: {
    name: 'French Polynesia',
    dial_code: 689,
  },
  GA: {
    name: 'Gabon',
    dial_code: 241,
  },
  GE: {
    name: 'Georgia',
    dial_code: 995,
  },
  DE: {
    name: 'Germany',
    dial_code: 49,
  },
  GH: {
    name: 'Ghana',
    dial_code: 233,
  },
  GI: {
    name: 'Gibraltar',
    dial_code: 350,
  },
  GR: {
    name: 'Greece',
    dial_code: 30,
  },
  GL: {
    name: 'Greenland',
    dial_code: 299,
  },
  GD: {
    name: 'Grenada',
    dial_code: 1,
  },
  GP: {
    name: 'Guadeloupe',
    dial_code: 590,
  },
  GU: {
    name: 'Guam',
    dial_code: 1,
  },
  GT: {
    name: 'Guatemala',
    dial_code: 502,
  },
  GN: {
    name: 'Guinea',
    dial_code: 224,
  },
  GW: {
    name: 'Guinea-Bissau',
    dial_code: 245,
  },
  GY: {
    name: 'Guyana',
    dial_code: 592,
  },
  HT: {
    name: 'Haiti',
    dial_code: 509,
  },
  HN: {
    name: 'Honduras',
    dial_code: 504,
  },
  HK: {
    name: 'Hong Kong',
    dial_code: 852,
  },
  HU: {
    name: 'Hungary',
    dial_code: 36,
  },
  IS: {
    name: 'Iceland',
    dial_code: 354,
  },
  IN: {
    name: 'India',
    dial_code: 91,
  },
  ID: {
    name: 'Indonesia',
    dial_code: 62,
  },
  IR: {
    name: 'Iran',
    dial_code: 98,
  },
  IQ: {
    name: 'Iraq',
    dial_code: 964,
  },
  IE: {
    name: 'Ireland',
    dial_code: 353,
  },
  IL: {
    name: 'Israel',
    dial_code: 972,
  },
  IT: {
    name: 'Italy',
    dial_code: 39,
  },
  JM: {
    name: 'Jamaica',
    dial_code: 1,
  },
  JP: {
    name: 'Japan',
    dial_code: 81,
  },
  JO: {
    name: 'Jordan',
    dial_code: 962,
  },
  KZ: {
    name: 'Kazakhstan',
    dial_code: 7,
  },
  KE: {
    name: 'Kenya',
    dial_code: 254,
  },
  KI: {
    name: 'Kiribati',
    dial_code: 686,
  },
  XK: {
    name: 'Kosovo',
    dial_code: 381,
  },
  KW: {
    name: 'Kuwait',
    dial_code: 965,
  },
  KG: {
    name: 'Kyrgyzstan',
    dial_code: 996,
  },
  LA: {
    name: 'Laos',
    dial_code: 856,
  },
  LV: {
    name: 'Latvia',
    dial_code: 371,
  },
  LB: {
    name: 'Lebanon',
    dial_code: 961,
  },
  LS: {
    name: 'Lesotho',
    dial_code: 266,
  },
  LR: {
    name: 'Liberia',
    dial_code: 231,
  },
  LY: {
    name: 'Libya',
    dial_code: 218,
  },
  LI: {
    name: 'Liechtenstein',
    dial_code: 423,
  },
  LT: {
    name: 'Lithuania',
    dial_code: 370,
  },
  LU: {
    name: 'Luxembourg',
    dial_code: 352,
  },
  MO: {
    name: 'Macau',
    dial_code: 853,
  },
  MK: {
    name: 'Macedonia',
    dial_code: 389,
  },
  MG: {
    name: 'Madagascar',
    dial_code: 261,
  },
  MW: {
    name: 'Malawi',
    dial_code: 265,
  },
  MY: {
    name: 'Malaysia',
    dial_code: 60,
  },
  MV: {
    name: 'Maldives',
    dial_code: 960,
  },
  ML: {
    name: 'Mali',
    dial_code: 223,
  },
  MT: {
    name: 'Malta',
    dial_code: 356,
  },
  MH: {
    name: 'Marshall Islands',
    dial_code: 692,
  },
  MQ: {
    name: 'Martinique',
    dial_code: 596,
  },
  MR: {
    name: 'Mauritania',
    dial_code: 222,
  },
  MU: {
    name: 'Mauritius',
    dial_code: 230,
  },
  YT: {
    name: 'Mayotte',
    dial_code: 262,
  },
  MX: {
    name: 'Mexico',
    dial_code: 52,
  },
  MD: {
    name: 'Moldova',
    dial_code: 373,
  },
  MC: {
    name: 'Monaco',
    dial_code: 377,
  },
  MN: {
    name: 'Mongolia',
    dial_code: 976,
  },
  ME: {
    name: 'Montenegro',
    dial_code: 382,
  },
  MS: {
    name: 'Montserrat',
    dial_code: 1,
  },
  MA: {
    name: 'Morocco',
    dial_code: 212,
  },
  MZ: {
    name: 'Mozambique',
    dial_code: 258,
  },
  NA: {
    name: 'Namibia',
    dial_code: 264,
  },
  NR: {
    name: 'Nauru',
    dial_code: 674,
  },
  NP: {
    name: 'Nepal',
    dial_code: 977,
  },
  NL: {
    name: 'Netherlands',
    dial_code: 31,
  },
  AN: {
    name: 'Netherlands Antilles',
    dial_code: 599,
  },
  NC: {
    name: 'New Caledonia',
    dial_code: 687,
  },
  NZ: {
    name: 'New Zealand',
    dial_code: 64,
  },
  NI: {
    name: 'Nicaragua',
    dial_code: 505,
  },
  NE: {
    name: 'Niger',
    dial_code: 227,
  },
  NG: {
    name: 'Nigeria',
    dial_code: 234,
  },
  NU: {
    name: 'Niue',
    dial_code: 683,
  },
  NF: {
    name: 'Norfolk Island',
    dial_code: 672,
  },
  KP: {
    name: 'North Korea',
    dial_code: 850,
  },
  MP: {
    name: 'Northern Mariana Islands',
    dial_code: 1,
  },
  NO: {
    name: 'Norway',
    dial_code: 47,
  },
  OM: {
    name: 'Oman',
    dial_code: 968,
  },
  PK: {
    name: 'Pakistan',
    dial_code: 92,
  },
  PW: {
    name: 'Palau',
    dial_code: 680,
  },
  PS: {
    name: 'Palestine',
    dial_code: 970,
  },
  PA: {
    name: 'Panama',
    dial_code: 507,
  },
  PG: {
    name: 'Papua New Guinea',
    dial_code: 675,
  },
  PY: {
    name: 'Paraguay',
    dial_code: 595,
  },
  PE: {
    name: 'Peru',
    dial_code: 51,
  },
  PH: {
    name: 'Philippines',
    dial_code: 63,
  },
  PL: {
    name: 'Poland',
    dial_code: 48,
  },
  PT: {
    name: 'Portugal',
    dial_code: 351,
  },
  PR: {
    name: 'Puerto Rico',
    dial_code: 1,
  },
  QA: {
    name: 'Qatar',
    dial_code: 974,
  },
  CG: {
    name: 'Republic of the Congo',
    dial_code: 242,
  },
  RE: {
    name: 'Reunion',
    dial_code: 262,
  },
  RO: {
    name: 'Romania',
    dial_code: 40,
  },
  RU: {
    name: 'Russia',
    dial_code: 7,
  },
  RW: {
    name: 'Rwanda',
    dial_code: 250,
  },
  BL: {
    name: 'Saint Barthelemy',
    dial_code: 590,
  },
  SH: {
    name: 'Saint Helena',
    dial_code: 290,
  },
  KN: {
    name: 'Saint Kitts and Nevis',
    dial_code: 1,
  },
  MF: {
    name: 'Saint Martin',
    dial_code: 590,
  },
  PM: {
    name: 'Saint Pierre and Miquelon',
    dial_code: 508,
  },
  VC: {
    name: 'Saint Vincent and the Grenadines',
    dial_code: 1,
  },
  WS: {
    name: 'Samoa',
    dial_code: 685,
  },
  SM: {
    name: 'San Marino',
    dial_code: 378,
  },
  ST: {
    name: 'Sao Tome and Principe',
    dial_code: 239,
  },
  SA: {
    name: 'Saudi Arabia',
    dial_code: 966,
  },
  SN: {
    name: 'Senegal',
    dial_code: 221,
  },
  RS: {
    name: 'Serbia',
    dial_code: 381,
  },
  SC: {
    name: 'Seychelles',
    dial_code: 248,
  },
  SL: {
    name: 'Sierra Leone',
    dial_code: 232,
  },
  SG: {
    name: 'Singapore',
    dial_code: 65,
  },
  SK: {
    name: 'Slovakia',
    dial_code: 421,
  },
  SI: {
    name: 'Slovenia',
    dial_code: 386,
  },
  SB: {
    name: 'Solomon Islands',
    dial_code: 677,
  },
  SO: {
    name: 'Somalia',
    dial_code: 252,
  },
  ZA: {
    name: 'South Africa',
    dial_code: 27,
  },
  KR: {
    name: 'South Korea',
    dial_code: 82,
  },
  ES: {
    name: 'Spain',
    dial_code: 34,
  },
  LK: {
    name: 'Sri Lanka',
    dial_code: 94,
  },
  LC: {
    name: 'St. Lucia',
    dial_code: 1,
  },
  SD: {
    name: 'Sudan',
    dial_code: 249,
  },
  SR: {
    name: 'Suriname',
    dial_code: 597,
  },
  SZ: {
    name: 'Swaziland',
    dial_code: 268,
  },
  SE: {
    name: 'Sweden',
    dial_code: 46,
  },
  CH: {
    name: 'Switzerland',
    dial_code: 41,
  },
  SY: {
    name: 'Syria',
    dial_code: 963,
  },
  TW: {
    name: 'Taiwan',
    dial_code: 886,
  },
  TJ: {
    name: 'Tajikistan',
    dial_code: 992,
  },
  TZ: {
    name: 'Tanzania',
    dial_code: 255,
  },
  TH: {
    name: 'Thailand',
    dial_code: 66,
  },
  BS: {
    name: 'The Bahamas',
    dial_code: 1,
  },
  GM: {
    name: 'The Gambia',
    dial_code: 220,
  },
  TL: {
    name: 'Timor-Leste',
    dial_code: 670,
  },
  TG: {
    name: 'Togo',
    dial_code: 228,
  },
  TK: {
    name: 'Tokelau',
    dial_code: 690,
  },
  TO: {
    name: 'Tonga',
    dial_code: 676,
  },
  TT: {
    name: 'Trinidad and Tobago',
    dial_code: 1,
  },
  TN: {
    name: 'Tunisia',
    dial_code: 216,
  },
  TR: {
    name: 'Turkey',
    dial_code: 90,
  },
  TM: {
    name: 'Turkmenistan',
    dial_code: 993,
  },
  TC: {
    name: 'Turks and Caicos Islands',
    dial_code: 1,
  },
  TV: {
    name: 'Tuvalu',
    dial_code: 688,
  },
  UG: {
    name: 'Uganda',
    dial_code: 256,
  },
  UA: {
    name: 'Ukraine',
    dial_code: 380,
  },
  AE: {
    name: 'United Arab Emirates',
    dial_code: 971,
  },
  GB: {
    name: 'United Kingdom',
    dial_code: 44,
  },
  US: {
    name: 'United States',
    dial_code: 1,
  },
  UY: {
    name: 'Uruguay',
    dial_code: 598,
  },
  VI: {
    name: 'US Virgin Islands',
    dial_code: 1,
  },
  UZ: {
    name: 'Uzbekistan',
    dial_code: 998,
  },
  VU: {
    name: 'Vanuatu',
    dial_code: 678,
  },
  VA: {
    name: 'Vatican City',
    dial_code: 39,
  },
  VE: {
    name: 'Venezuela',
    dial_code: 58,
  },
  VN: {
    name: 'Vietnam',
    dial_code: 84,
  },
  WF: {
    name: 'Wallis and Futuna',
    dial_code: 681,
  },
  YE: {
    name: 'Yemen',
    dial_code: 967,
  },
  ZM: {
    name: 'Zambia',
    dial_code: 260,
  },
  ZW: {
    name: 'Zimbabwe',
    dial_code: 263,
  },
};

const emojiCodes = [
  {
    code: 'AD',
    emoji: '🇦🇩',
    unicode: 'U+1F1E6 U+1F1E9',
    name: 'Andorra',
    title: 'flag for Andorra',
  },
  {
    code: 'AE',
    emoji: '🇦🇪',
    unicode: 'U+1F1E6 U+1F1EA',
    name: 'United Arab Emirates',
    title: 'flag for United Arab Emirates',
  },
  {
    code: 'AF',
    emoji: '🇦🇫',
    unicode: 'U+1F1E6 U+1F1EB',
    name: 'Afghanistan',
    title: 'flag for Afghanistan',
  },
  {
    code: 'AG',
    emoji: '🇦🇬',
    unicode: 'U+1F1E6 U+1F1EC',
    name: 'Antigua and Barbuda',
    title: 'flag for Antigua and Barbuda',
  },
  {
    code: 'AI',
    emoji: '🇦🇮',
    unicode: 'U+1F1E6 U+1F1EE',
    name: 'Anguilla',
    title: 'flag for Anguilla',
  },
  {
    code: 'AL',
    emoji: '🇦🇱',
    unicode: 'U+1F1E6 U+1F1F1',
    name: 'Albania',
    title: 'flag for Albania',
  },
  {
    code: 'AM',
    emoji: '🇦🇲',
    unicode: 'U+1F1E6 U+1F1F2',
    name: 'Armenia',
    title: 'flag for Armenia',
  },
  {
    code: 'AO',
    emoji: '🇦🇴',
    unicode: 'U+1F1E6 U+1F1F4',
    name: 'Angola',
    title: 'flag for Angola',
  },
  {
    code: 'AQ',
    emoji: '🇦🇶',
    unicode: 'U+1F1E6 U+1F1F6',
    name: 'Antarctica',
    title: 'flag for Antarctica',
  },
  {
    code: 'AR',
    emoji: '🇦🇷',
    unicode: 'U+1F1E6 U+1F1F7',
    name: 'Argentina',
    title: 'flag for Argentina',
  },
  {
    code: 'AS',
    emoji: '🇦🇸',
    unicode: 'U+1F1E6 U+1F1F8',
    name: 'American Samoa',
    title: 'flag for American Samoa',
  },
  {
    code: 'AT',
    emoji: '🇦🇹',
    unicode: 'U+1F1E6 U+1F1F9',
    name: 'Austria',
    title: 'flag for Austria',
  },
  {
    code: 'AU',
    emoji: '🇦🇺',
    unicode: 'U+1F1E6 U+1F1FA',
    name: 'Australia',
    title: 'flag for Australia',
  },
  {
    code: 'AW',
    emoji: '🇦🇼',
    unicode: 'U+1F1E6 U+1F1FC',
    name: 'Aruba',
    title: 'flag for Aruba',
  },
  {
    code: 'AX',
    emoji: '🇦🇽',
    unicode: 'U+1F1E6 U+1F1FD',
    name: 'Åland Islands',
    title: 'flag for Åland Islands',
  },
  {
    code: 'AZ',
    emoji: '🇦🇿',
    unicode: 'U+1F1E6 U+1F1FF',
    name: 'Azerbaijan',
    title: 'flag for Azerbaijan',
  },
  {
    code: 'BA',
    emoji: '🇧🇦',
    unicode: 'U+1F1E7 U+1F1E6',
    name: 'Bosnia and Herzegovina',
    title: 'flag for Bosnia and Herzegovina',
  },
  {
    code: 'BB',
    emoji: '🇧🇧',
    unicode: 'U+1F1E7 U+1F1E7',
    name: 'Barbados',
    title: 'flag for Barbados',
  },
  {
    code: 'BD',
    emoji: '🇧🇩',
    unicode: 'U+1F1E7 U+1F1E9',
    name: 'Bangladesh',
    title: 'flag for Bangladesh',
  },
  {
    code: 'BE',
    emoji: '🇧🇪',
    unicode: 'U+1F1E7 U+1F1EA',
    name: 'Belgium',
    title: 'flag for Belgium',
  },
  {
    code: 'BF',
    emoji: '🇧🇫',
    unicode: 'U+1F1E7 U+1F1EB',
    name: 'Burkina Faso',
    title: 'flag for Burkina Faso',
  },
  {
    code: 'BG',
    emoji: '🇧🇬',
    unicode: 'U+1F1E7 U+1F1EC',
    name: 'Bulgaria',
    title: 'flag for Bulgaria',
  },
  {
    code: 'BH',
    emoji: '🇧🇭',
    unicode: 'U+1F1E7 U+1F1ED',
    name: 'Bahrain',
    title: 'flag for Bahrain',
  },
  {
    code: 'BI',
    emoji: '🇧🇮',
    unicode: 'U+1F1E7 U+1F1EE',
    name: 'Burundi',
    title: 'flag for Burundi',
  },
  {
    code: 'BJ',
    emoji: '🇧🇯',
    unicode: 'U+1F1E7 U+1F1EF',
    name: 'Benin',
    title: 'flag for Benin',
  },
  {
    code: 'BL',
    emoji: '🇧🇱',
    unicode: 'U+1F1E7 U+1F1F1',
    name: 'Saint Barthélemy',
    title: 'flag for Saint Barthélemy',
  },
  {
    code: 'BM',
    emoji: '🇧🇲',
    unicode: 'U+1F1E7 U+1F1F2',
    name: 'Bermuda',
    title: 'flag for Bermuda',
  },
  {
    code: 'BN',
    emoji: '🇧🇳',
    unicode: 'U+1F1E7 U+1F1F3',
    name: 'Brunei Darussalam',
    title: 'flag for Brunei Darussalam',
  },
  {
    code: 'BO',
    emoji: '🇧🇴',
    unicode: 'U+1F1E7 U+1F1F4',
    name: 'Bolivia',
    title: 'flag for Bolivia',
  },
  {
    code: 'BQ',
    emoji: '🇧🇶',
    unicode: 'U+1F1E7 U+1F1F6',
    name: 'Bonaire, Sint Eustatius and Saba',
    title: 'flag for Bonaire, Sint Eustatius and Saba',
  },
  {
    code: 'BR',
    emoji: '🇧🇷',
    unicode: 'U+1F1E7 U+1F1F7',
    name: 'Brazil',
    title: 'flag for Brazil',
  },
  {
    code: 'BS',
    emoji: '🇧🇸',
    unicode: 'U+1F1E7 U+1F1F8',
    name: 'Bahamas',
    title: 'flag for Bahamas',
  },
  {
    code: 'BT',
    emoji: '🇧🇹',
    unicode: 'U+1F1E7 U+1F1F9',
    name: 'Bhutan',
    title: 'flag for Bhutan',
  },
  {
    code: 'BV',
    emoji: '🇧🇻',
    unicode: 'U+1F1E7 U+1F1FB',
    name: 'Bouvet Island',
    title: 'flag for Bouvet Island',
  },
  {
    code: 'BW',
    emoji: '🇧🇼',
    unicode: 'U+1F1E7 U+1F1FC',
    name: 'Botswana',
    title: 'flag for Botswana',
  },
  {
    code: 'BY',
    emoji: '🇧🇾',
    unicode: 'U+1F1E7 U+1F1FE',
    name: 'Belarus',
    title: 'flag for Belarus',
  },
  {
    code: 'BZ',
    emoji: '🇧🇿',
    unicode: 'U+1F1E7 U+1F1FF',
    name: 'Belize',
    title: 'flag for Belize',
  },
  {
    code: 'CA',
    emoji: '🇨🇦',
    unicode: 'U+1F1E8 U+1F1E6',
    name: 'Canada',
    title: 'flag for Canada',
  },
  {
    code: 'CC',
    emoji: '🇨🇨',
    unicode: 'U+1F1E8 U+1F1E8',
    name: 'Cocos (Keeling) Islands',
    title: 'flag for Cocos (Keeling) Islands',
  },
  {
    code: 'CD',
    emoji: '🇨🇩',
    unicode: 'U+1F1E8 U+1F1E9',
    name: 'Congo',
    title: 'flag for Congo',
  },
  {
    code: 'CF',
    emoji: '🇨🇫',
    unicode: 'U+1F1E8 U+1F1EB',
    name: 'Central African Republic',
    title: 'flag for Central African Republic',
  },
  {
    code: 'CG',
    emoji: '🇨🇬',
    unicode: 'U+1F1E8 U+1F1EC',
    name: 'Congo',
    title: 'flag for Congo',
  },
  {
    code: 'CH',
    emoji: '🇨🇭',
    unicode: 'U+1F1E8 U+1F1ED',
    name: 'Switzerland',
    title: 'flag for Switzerland',
  },
  {
    code: 'CI',
    emoji: '🇨🇮',
    unicode: 'U+1F1E8 U+1F1EE',
    name: "Côte D'Ivoire",
    title: "flag for Côte D'Ivoire",
  },
  {
    code: 'CK',
    emoji: '🇨🇰',
    unicode: 'U+1F1E8 U+1F1F0',
    name: 'Cook Islands',
    title: 'flag for Cook Islands',
  },
  {
    code: 'CL',
    emoji: '🇨🇱',
    unicode: 'U+1F1E8 U+1F1F1',
    name: 'Chile',
    title: 'flag for Chile',
  },
  {
    code: 'CM',
    emoji: '🇨🇲',
    unicode: 'U+1F1E8 U+1F1F2',
    name: 'Cameroon',
    title: 'flag for Cameroon',
  },
  {
    code: 'CN',
    emoji: '🇨🇳',
    unicode: 'U+1F1E8 U+1F1F3',
    name: 'China',
    title: 'flag for China',
  },
  {
    code: 'CO',
    emoji: '🇨🇴',
    unicode: 'U+1F1E8 U+1F1F4',
    name: 'Colombia',
    title: 'flag for Colombia',
  },
  {
    code: 'CR',
    emoji: '🇨🇷',
    unicode: 'U+1F1E8 U+1F1F7',
    name: 'Costa Rica',
    title: 'flag for Costa Rica',
  },
  {
    code: 'CU',
    emoji: '🇨🇺',
    unicode: 'U+1F1E8 U+1F1FA',
    name: 'Cuba',
    title: 'flag for Cuba',
  },
  {
    code: 'CV',
    emoji: '🇨🇻',
    unicode: 'U+1F1E8 U+1F1FB',
    name: 'Cape Verde',
    title: 'flag for Cape Verde',
  },
  {
    code: 'CW',
    emoji: '🇨🇼',
    unicode: 'U+1F1E8 U+1F1FC',
    name: 'Curaçao',
    title: 'flag for Curaçao',
  },
  {
    code: 'CX',
    emoji: '🇨🇽',
    unicode: 'U+1F1E8 U+1F1FD',
    name: 'Christmas Island',
    title: 'flag for Christmas Island',
  },
  {
    code: 'CY',
    emoji: '🇨🇾',
    unicode: 'U+1F1E8 U+1F1FE',
    name: 'Cyprus',
    title: 'flag for Cyprus',
  },
  {
    code: 'CZ',
    emoji: '🇨🇿',
    unicode: 'U+1F1E8 U+1F1FF',
    name: 'Czech Republic',
    title: 'flag for Czech Republic',
  },
  {
    code: 'DE',
    emoji: '🇩🇪',
    unicode: 'U+1F1E9 U+1F1EA',
    name: 'Germany',
    title: 'flag for Germany',
  },
  {
    code: 'DJ',
    emoji: '🇩🇯',
    unicode: 'U+1F1E9 U+1F1EF',
    name: 'Djibouti',
    title: 'flag for Djibouti',
  },
  {
    code: 'DK',
    emoji: '🇩🇰',
    unicode: 'U+1F1E9 U+1F1F0',
    name: 'Denmark',
    title: 'flag for Denmark',
  },
  {
    code: 'DM',
    emoji: '🇩🇲',
    unicode: 'U+1F1E9 U+1F1F2',
    name: 'Dominica',
    title: 'flag for Dominica',
  },
  {
    code: 'DO',
    emoji: '🇩🇴',
    unicode: 'U+1F1E9 U+1F1F4',
    name: 'Dominican Republic',
    title: 'flag for Dominican Republic',
  },
  {
    code: 'DZ',
    emoji: '🇩🇿',
    unicode: 'U+1F1E9 U+1F1FF',
    name: 'Algeria',
    title: 'flag for Algeria',
  },
  {
    code: 'EC',
    emoji: '🇪🇨',
    unicode: 'U+1F1EA U+1F1E8',
    name: 'Ecuador',
    title: 'flag for Ecuador',
  },
  {
    code: 'EE',
    emoji: '🇪🇪',
    unicode: 'U+1F1EA U+1F1EA',
    name: 'Estonia',
    title: 'flag for Estonia',
  },
  {
    code: 'EG',
    emoji: '🇪🇬',
    unicode: 'U+1F1EA U+1F1EC',
    name: 'Egypt',
    title: 'flag for Egypt',
  },
  {
    code: 'EH',
    emoji: '🇪🇭',
    unicode: 'U+1F1EA U+1F1ED',
    name: 'Western Sahara',
    title: 'flag for Western Sahara',
  },
  {
    code: 'ER',
    emoji: '🇪🇷',
    unicode: 'U+1F1EA U+1F1F7',
    name: 'Eritrea',
    title: 'flag for Eritrea',
  },
  {
    code: 'ES',
    emoji: '🇪🇸',
    unicode: 'U+1F1EA U+1F1F8',
    name: 'Spain',
    title: 'flag for Spain',
  },
  {
    code: 'ET',
    emoji: '🇪🇹',
    unicode: 'U+1F1EA U+1F1F9',
    name: 'Ethiopia',
    title: 'flag for Ethiopia',
  },
  {
    code: 'EU',
    emoji: '🇪🇺',
    unicode: 'U+1F1EA U+1F1FA',
    name: 'European Union',
    title: 'flag for European Union',
  },
  {
    code: 'FI',
    emoji: '🇫🇮',
    unicode: 'U+1F1EB U+1F1EE',
    name: 'Finland',
    title: 'flag for Finland',
  },
  {
    code: 'FJ',
    emoji: '🇫🇯',
    unicode: 'U+1F1EB U+1F1EF',
    name: 'Fiji',
    title: 'flag for Fiji',
  },
  {
    code: 'FK',
    emoji: '🇫🇰',
    unicode: 'U+1F1EB U+1F1F0',
    name: 'Falkland Islands (Malvinas)',
    title: 'flag for Falkland Islands (Malvinas)',
  },
  {
    code: 'FM',
    emoji: '🇫🇲',
    unicode: 'U+1F1EB U+1F1F2',
    name: 'Micronesia',
    title: 'flag for Micronesia',
  },
  {
    code: 'FO',
    emoji: '🇫🇴',
    unicode: 'U+1F1EB U+1F1F4',
    name: 'Faroe Islands',
    title: 'flag for Faroe Islands',
  },
  {
    code: 'FR',
    emoji: '🇫🇷',
    unicode: 'U+1F1EB U+1F1F7',
    name: 'France',
    title: 'flag for France',
  },
  {
    code: 'GA',
    emoji: '🇬🇦',
    unicode: 'U+1F1EC U+1F1E6',
    name: 'Gabon',
    title: 'flag for Gabon',
  },
  {
    code: 'GB',
    emoji: '🇬🇧',
    unicode: 'U+1F1EC U+1F1E7',
    name: 'United Kingdom',
    title: 'flag for United Kingdom',
  },
  {
    code: 'GD',
    emoji: '🇬🇩',
    unicode: 'U+1F1EC U+1F1E9',
    name: 'Grenada',
    title: 'flag for Grenada',
  },
  {
    code: 'GE',
    emoji: '🇬🇪',
    unicode: 'U+1F1EC U+1F1EA',
    name: 'Georgia',
    title: 'flag for Georgia',
  },
  {
    code: 'GF',
    emoji: '🇬🇫',
    unicode: 'U+1F1EC U+1F1EB',
    name: 'French Guiana',
    title: 'flag for French Guiana',
  },
  {
    code: 'GG',
    emoji: '🇬🇬',
    unicode: 'U+1F1EC U+1F1EC',
    name: 'Guernsey',
    title: 'flag for Guernsey',
  },
  {
    code: 'GH',
    emoji: '🇬🇭',
    unicode: 'U+1F1EC U+1F1ED',
    name: 'Ghana',
    title: 'flag for Ghana',
  },
  {
    code: 'GI',
    emoji: '🇬🇮',
    unicode: 'U+1F1EC U+1F1EE',
    name: 'Gibraltar',
    title: 'flag for Gibraltar',
  },
  {
    code: 'GL',
    emoji: '🇬🇱',
    unicode: 'U+1F1EC U+1F1F1',
    name: 'Greenland',
    title: 'flag for Greenland',
  },
  {
    code: 'GM',
    emoji: '🇬🇲',
    unicode: 'U+1F1EC U+1F1F2',
    name: 'Gambia',
    title: 'flag for Gambia',
  },
  {
    code: 'GN',
    emoji: '🇬🇳',
    unicode: 'U+1F1EC U+1F1F3',
    name: 'Guinea',
    title: 'flag for Guinea',
  },
  {
    code: 'GP',
    emoji: '🇬🇵',
    unicode: 'U+1F1EC U+1F1F5',
    name: 'Guadeloupe',
    title: 'flag for Guadeloupe',
  },
  {
    code: 'GQ',
    emoji: '🇬🇶',
    unicode: 'U+1F1EC U+1F1F6',
    name: 'Equatorial Guinea',
    title: 'flag for Equatorial Guinea',
  },
  {
    code: 'GR',
    emoji: '🇬🇷',
    unicode: 'U+1F1EC U+1F1F7',
    name: 'Greece',
    title: 'flag for Greece',
  },
  {
    code: 'GS',
    emoji: '🇬🇸',
    unicode: 'U+1F1EC U+1F1F8',
    name: 'South Georgia',
    title: 'flag for South Georgia',
  },
  {
    code: 'GT',
    emoji: '🇬🇹',
    unicode: 'U+1F1EC U+1F1F9',
    name: 'Guatemala',
    title: 'flag for Guatemala',
  },
  {
    code: 'GU',
    emoji: '🇬🇺',
    unicode: 'U+1F1EC U+1F1FA',
    name: 'Guam',
    title: 'flag for Guam',
  },
  {
    code: 'GW',
    emoji: '🇬🇼',
    unicode: 'U+1F1EC U+1F1FC',
    name: 'Guinea-Bissau',
    title: 'flag for Guinea-Bissau',
  },
  {
    code: 'GY',
    emoji: '🇬🇾',
    unicode: 'U+1F1EC U+1F1FE',
    name: 'Guyana',
    title: 'flag for Guyana',
  },
  {
    code: 'HK',
    emoji: '🇭🇰',
    unicode: 'U+1F1ED U+1F1F0',
    name: 'Hong Kong',
    title: 'flag for Hong Kong',
  },
  {
    code: 'HM',
    emoji: '🇭🇲',
    unicode: 'U+1F1ED U+1F1F2',
    name: 'Heard Island and Mcdonald Islands',
    title: 'flag for Heard Island and Mcdonald Islands',
  },
  {
    code: 'HN',
    emoji: '🇭🇳',
    unicode: 'U+1F1ED U+1F1F3',
    name: 'Honduras',
    title: 'flag for Honduras',
  },
  {
    code: 'HR',
    emoji: '🇭🇷',
    unicode: 'U+1F1ED U+1F1F7',
    name: 'Croatia',
    title: 'flag for Croatia',
  },
  {
    code: 'HT',
    emoji: '🇭🇹',
    unicode: 'U+1F1ED U+1F1F9',
    name: 'Haiti',
    title: 'flag for Haiti',
  },
  {
    code: 'HU',
    emoji: '🇭🇺',
    unicode: 'U+1F1ED U+1F1FA',
    name: 'Hungary',
    title: 'flag for Hungary',
  },
  {
    code: 'ID',
    emoji: '🇮🇩',
    unicode: 'U+1F1EE U+1F1E9',
    name: 'Indonesia',
    title: 'flag for Indonesia',
  },
  {
    code: 'IE',
    emoji: '🇮🇪',
    unicode: 'U+1F1EE U+1F1EA',
    name: 'Ireland',
    title: 'flag for Ireland',
  },
  {
    code: 'IL',
    emoji: '🇮🇱',
    unicode: 'U+1F1EE U+1F1F1',
    name: 'Israel',
    title: 'flag for Israel',
  },
  {
    code: 'IM',
    emoji: '🇮🇲',
    unicode: 'U+1F1EE U+1F1F2',
    name: 'Isle of Man',
    title: 'flag for Isle of Man',
  },
  {
    code: 'IN',
    emoji: '🇮🇳',
    unicode: 'U+1F1EE U+1F1F3',
    name: 'India',
    title: 'flag for India',
  },
  {
    code: 'IO',
    emoji: '🇮🇴',
    unicode: 'U+1F1EE U+1F1F4',
    name: 'British Indian Ocean Territory',
    title: 'flag for British Indian Ocean Territory',
  },
  {
    code: 'IQ',
    emoji: '🇮🇶',
    unicode: 'U+1F1EE U+1F1F6',
    name: 'Iraq',
    title: 'flag for Iraq',
  },
  {
    code: 'IR',
    emoji: '🇮🇷',
    unicode: 'U+1F1EE U+1F1F7',
    name: 'Iran',
    title: 'flag for Iran',
  },
  {
    code: 'IS',
    emoji: '🇮🇸',
    unicode: 'U+1F1EE U+1F1F8',
    name: 'Iceland',
    title: 'flag for Iceland',
  },
  {
    code: 'IT',
    emoji: '🇮🇹',
    unicode: 'U+1F1EE U+1F1F9',
    name: 'Italy',
    title: 'flag for Italy',
  },
  {
    code: 'JE',
    emoji: '🇯🇪',
    unicode: 'U+1F1EF U+1F1EA',
    name: 'Jersey',
    title: 'flag for Jersey',
  },
  {
    code: 'JM',
    emoji: '🇯🇲',
    unicode: 'U+1F1EF U+1F1F2',
    name: 'Jamaica',
    title: 'flag for Jamaica',
  },
  {
    code: 'JO',
    emoji: '🇯🇴',
    unicode: 'U+1F1EF U+1F1F4',
    name: 'Jordan',
    title: 'flag for Jordan',
  },
  {
    code: 'JP',
    emoji: '🇯🇵',
    unicode: 'U+1F1EF U+1F1F5',
    name: 'Japan',
    title: 'flag for Japan',
  },
  {
    code: 'KE',
    emoji: '🇰🇪',
    unicode: 'U+1F1F0 U+1F1EA',
    name: 'Kenya',
    title: 'flag for Kenya',
  },
  {
    code: 'KG',
    emoji: '🇰🇬',
    unicode: 'U+1F1F0 U+1F1EC',
    name: 'Kyrgyzstan',
    title: 'flag for Kyrgyzstan',
  },
  {
    code: 'KH',
    emoji: '🇰🇭',
    unicode: 'U+1F1F0 U+1F1ED',
    name: 'Cambodia',
    title: 'flag for Cambodia',
  },
  {
    code: 'KI',
    emoji: '🇰🇮',
    unicode: 'U+1F1F0 U+1F1EE',
    name: 'Kiribati',
    title: 'flag for Kiribati',
  },
  {
    code: 'KM',
    emoji: '🇰🇲',
    unicode: 'U+1F1F0 U+1F1F2',
    name: 'Comoros',
    title: 'flag for Comoros',
  },
  {
    code: 'KN',
    emoji: '🇰🇳',
    unicode: 'U+1F1F0 U+1F1F3',
    name: 'Saint Kitts and Nevis',
    title: 'flag for Saint Kitts and Nevis',
  },
  {
    code: 'KP',
    emoji: '🇰🇵',
    unicode: 'U+1F1F0 U+1F1F5',
    name: 'North Korea',
    title: 'flag for North Korea',
  },
  {
    code: 'KR',
    emoji: '🇰🇷',
    unicode: 'U+1F1F0 U+1F1F7',
    name: 'South Korea',
    title: 'flag for South Korea',
  },
  {
    code: 'KW',
    emoji: '🇰🇼',
    unicode: 'U+1F1F0 U+1F1FC',
    name: 'Kuwait',
    title: 'flag for Kuwait',
  },
  {
    code: 'KY',
    emoji: '🇰🇾',
    unicode: 'U+1F1F0 U+1F1FE',
    name: 'Cayman Islands',
    title: 'flag for Cayman Islands',
  },
  {
    code: 'KZ',
    emoji: '🇰🇿',
    unicode: 'U+1F1F0 U+1F1FF',
    name: 'Kazakhstan',
    title: 'flag for Kazakhstan',
  },
  {
    code: 'LA',
    emoji: '🇱🇦',
    unicode: 'U+1F1F1 U+1F1E6',
    name: "Lao People's Democratic Republic",
    title: "flag for Lao People's Democratic Republic",
  },
  {
    code: 'LB',
    emoji: '🇱🇧',
    unicode: 'U+1F1F1 U+1F1E7',
    name: 'Lebanon',
    title: 'flag for Lebanon',
  },
  {
    code: 'LC',
    emoji: '🇱🇨',
    unicode: 'U+1F1F1 U+1F1E8',
    name: 'Saint Lucia',
    title: 'flag for Saint Lucia',
  },
  {
    code: 'LI',
    emoji: '🇱🇮',
    unicode: 'U+1F1F1 U+1F1EE',
    name: 'Liechtenstein',
    title: 'flag for Liechtenstein',
  },
  {
    code: 'LK',
    emoji: '🇱🇰',
    unicode: 'U+1F1F1 U+1F1F0',
    name: 'Sri Lanka',
    title: 'flag for Sri Lanka',
  },
  {
    code: 'LR',
    emoji: '🇱🇷',
    unicode: 'U+1F1F1 U+1F1F7',
    name: 'Liberia',
    title: 'flag for Liberia',
  },
  {
    code: 'LS',
    emoji: '🇱🇸',
    unicode: 'U+1F1F1 U+1F1F8',
    name: 'Lesotho',
    title: 'flag for Lesotho',
  },
  {
    code: 'LT',
    emoji: '🇱🇹',
    unicode: 'U+1F1F1 U+1F1F9',
    name: 'Lithuania',
    title: 'flag for Lithuania',
  },
  {
    code: 'LU',
    emoji: '🇱🇺',
    unicode: 'U+1F1F1 U+1F1FA',
    name: 'Luxembourg',
    title: 'flag for Luxembourg',
  },
  {
    code: 'LV',
    emoji: '🇱🇻',
    unicode: 'U+1F1F1 U+1F1FB',
    name: 'Latvia',
    title: 'flag for Latvia',
  },
  {
    code: 'LY',
    emoji: '🇱🇾',
    unicode: 'U+1F1F1 U+1F1FE',
    name: 'Libya',
    title: 'flag for Libya',
  },
  {
    code: 'MA',
    emoji: '🇲🇦',
    unicode: 'U+1F1F2 U+1F1E6',
    name: 'Morocco',
    title: 'flag for Morocco',
  },
  {
    code: 'MC',
    emoji: '🇲🇨',
    unicode: 'U+1F1F2 U+1F1E8',
    name: 'Monaco',
    title: 'flag for Monaco',
  },
  {
    code: 'MD',
    emoji: '🇲🇩',
    unicode: 'U+1F1F2 U+1F1E9',
    name: 'Moldova',
    title: 'flag for Moldova',
  },
  {
    code: 'ME',
    emoji: '🇲🇪',
    unicode: 'U+1F1F2 U+1F1EA',
    name: 'Montenegro',
    title: 'flag for Montenegro',
  },
  {
    code: 'MF',
    emoji: '🇲🇫',
    unicode: 'U+1F1F2 U+1F1EB',
    name: 'Saint Martin (French Part)',
    title: 'flag for Saint Martin (French Part)',
  },
  {
    code: 'MG',
    emoji: '🇲🇬',
    unicode: 'U+1F1F2 U+1F1EC',
    name: 'Madagascar',
    title: 'flag for Madagascar',
  },
  {
    code: 'MH',
    emoji: '🇲🇭',
    unicode: 'U+1F1F2 U+1F1ED',
    name: 'Marshall Islands',
    title: 'flag for Marshall Islands',
  },
  {
    code: 'MK',
    emoji: '🇲🇰',
    unicode: 'U+1F1F2 U+1F1F0',
    name: 'Macedonia',
    title: 'flag for Macedonia',
  },
  {
    code: 'ML',
    emoji: '🇲🇱',
    unicode: 'U+1F1F2 U+1F1F1',
    name: 'Mali',
    title: 'flag for Mali',
  },
  {
    code: 'MM',
    emoji: '🇲🇲',
    unicode: 'U+1F1F2 U+1F1F2',
    name: 'Myanmar',
    title: 'flag for Myanmar',
  },
  {
    code: 'MN',
    emoji: '🇲🇳',
    unicode: 'U+1F1F2 U+1F1F3',
    name: 'Mongolia',
    title: 'flag for Mongolia',
  },
  {
    code: 'MO',
    emoji: '🇲🇴',
    unicode: 'U+1F1F2 U+1F1F4',
    name: 'Macao',
    title: 'flag for Macao',
  },
  {
    code: 'MP',
    emoji: '🇲🇵',
    unicode: 'U+1F1F2 U+1F1F5',
    name: 'Northern Mariana Islands',
    title: 'flag for Northern Mariana Islands',
  },
  {
    code: 'MQ',
    emoji: '🇲🇶',
    unicode: 'U+1F1F2 U+1F1F6',
    name: 'Martinique',
    title: 'flag for Martinique',
  },
  {
    code: 'MR',
    emoji: '🇲🇷',
    unicode: 'U+1F1F2 U+1F1F7',
    name: 'Mauritania',
    title: 'flag for Mauritania',
  },
  {
    code: 'MS',
    emoji: '🇲🇸',
    unicode: 'U+1F1F2 U+1F1F8',
    name: 'Montserrat',
    title: 'flag for Montserrat',
  },
  {
    code: 'MT',
    emoji: '🇲🇹',
    unicode: 'U+1F1F2 U+1F1F9',
    name: 'Malta',
    title: 'flag for Malta',
  },
  {
    code: 'MU',
    emoji: '🇲🇺',
    unicode: 'U+1F1F2 U+1F1FA',
    name: 'Mauritius',
    title: 'flag for Mauritius',
  },
  {
    code: 'MV',
    emoji: '🇲🇻',
    unicode: 'U+1F1F2 U+1F1FB',
    name: 'Maldives',
    title: 'flag for Maldives',
  },
  {
    code: 'MW',
    emoji: '🇲🇼',
    unicode: 'U+1F1F2 U+1F1FC',
    name: 'Malawi',
    title: 'flag for Malawi',
  },
  {
    code: 'MX',
    emoji: '🇲🇽',
    unicode: 'U+1F1F2 U+1F1FD',
    name: 'Mexico',
    title: 'flag for Mexico',
  },
  {
    code: 'MY',
    emoji: '🇲🇾',
    unicode: 'U+1F1F2 U+1F1FE',
    name: 'Malaysia',
    title: 'flag for Malaysia',
  },
  {
    code: 'MZ',
    emoji: '🇲🇿',
    unicode: 'U+1F1F2 U+1F1FF',
    name: 'Mozambique',
    title: 'flag for Mozambique',
  },
  {
    code: 'NA',
    emoji: '🇳🇦',
    unicode: 'U+1F1F3 U+1F1E6',
    name: 'Namibia',
    title: 'flag for Namibia',
  },
  {
    code: 'NC',
    emoji: '🇳🇨',
    unicode: 'U+1F1F3 U+1F1E8',
    name: 'New Caledonia',
    title: 'flag for New Caledonia',
  },
  {
    code: 'NE',
    emoji: '🇳🇪',
    unicode: 'U+1F1F3 U+1F1EA',
    name: 'Niger',
    title: 'flag for Niger',
  },
  {
    code: 'NF',
    emoji: '🇳🇫',
    unicode: 'U+1F1F3 U+1F1EB',
    name: 'Norfolk Island',
    title: 'flag for Norfolk Island',
  },
  {
    code: 'NG',
    emoji: '🇳🇬',
    unicode: 'U+1F1F3 U+1F1EC',
    name: 'Nigeria',
    title: 'flag for Nigeria',
  },
  {
    code: 'NI',
    emoji: '🇳🇮',
    unicode: 'U+1F1F3 U+1F1EE',
    name: 'Nicaragua',
    title: 'flag for Nicaragua',
  },
  {
    code: 'NL',
    emoji: '🇳🇱',
    unicode: 'U+1F1F3 U+1F1F1',
    name: 'Netherlands',
    title: 'flag for Netherlands',
  },
  {
    code: 'NO',
    emoji: '🇳🇴',
    unicode: 'U+1F1F3 U+1F1F4',
    name: 'Norway',
    title: 'flag for Norway',
  },
  {
    code: 'NP',
    emoji: '🇳🇵',
    unicode: 'U+1F1F3 U+1F1F5',
    name: 'Nepal',
    title: 'flag for Nepal',
  },
  {
    code: 'NR',
    emoji: '🇳🇷',
    unicode: 'U+1F1F3 U+1F1F7',
    name: 'Nauru',
    title: 'flag for Nauru',
  },
  {
    code: 'NU',
    emoji: '🇳🇺',
    unicode: 'U+1F1F3 U+1F1FA',
    name: 'Niue',
    title: 'flag for Niue',
  },
  {
    code: 'NZ',
    emoji: '🇳🇿',
    unicode: 'U+1F1F3 U+1F1FF',
    name: 'New Zealand',
    title: 'flag for New Zealand',
  },
  {
    code: 'OM',
    emoji: '🇴🇲',
    unicode: 'U+1F1F4 U+1F1F2',
    name: 'Oman',
    title: 'flag for Oman',
  },
  {
    code: 'PA',
    emoji: '🇵🇦',
    unicode: 'U+1F1F5 U+1F1E6',
    name: 'Panama',
    title: 'flag for Panama',
  },
  {
    code: 'PE',
    emoji: '🇵🇪',
    unicode: 'U+1F1F5 U+1F1EA',
    name: 'Peru',
    title: 'flag for Peru',
  },
  {
    code: 'PF',
    emoji: '🇵🇫',
    unicode: 'U+1F1F5 U+1F1EB',
    name: 'French Polynesia',
    title: 'flag for French Polynesia',
  },
  {
    code: 'PG',
    emoji: '🇵🇬',
    unicode: 'U+1F1F5 U+1F1EC',
    name: 'Papua New Guinea',
    title: 'flag for Papua New Guinea',
  },
  {
    code: 'PH',
    emoji: '🇵🇭',
    unicode: 'U+1F1F5 U+1F1ED',
    name: 'Philippines',
    title: 'flag for Philippines',
  },
  {
    code: 'PK',
    emoji: '🇵🇰',
    unicode: 'U+1F1F5 U+1F1F0',
    name: 'Pakistan',
    title: 'flag for Pakistan',
  },
  {
    code: 'PL',
    emoji: '🇵🇱',
    unicode: 'U+1F1F5 U+1F1F1',
    name: 'Poland',
    title: 'flag for Poland',
  },
  {
    code: 'PM',
    emoji: '🇵🇲',
    unicode: 'U+1F1F5 U+1F1F2',
    name: 'Saint Pierre and Miquelon',
    title: 'flag for Saint Pierre and Miquelon',
  },
  {
    code: 'PN',
    emoji: '🇵🇳',
    unicode: 'U+1F1F5 U+1F1F3',
    name: 'Pitcairn',
    title: 'flag for Pitcairn',
  },
  {
    code: 'PR',
    emoji: '🇵🇷',
    unicode: 'U+1F1F5 U+1F1F7',
    name: 'Puerto Rico',
    title: 'flag for Puerto Rico',
  },
  {
    code: 'PS',
    emoji: '🇵🇸',
    unicode: 'U+1F1F5 U+1F1F8',
    name: 'Palestinian Territory',
    title: 'flag for Palestinian Territory',
  },
  {
    code: 'PT',
    emoji: '🇵🇹',
    unicode: 'U+1F1F5 U+1F1F9',
    name: 'Portugal',
    title: 'flag for Portugal',
  },
  {
    code: 'PW',
    emoji: '🇵🇼',
    unicode: 'U+1F1F5 U+1F1FC',
    name: 'Palau',
    title: 'flag for Palau',
  },
  {
    code: 'PY',
    emoji: '🇵🇾',
    unicode: 'U+1F1F5 U+1F1FE',
    name: 'Paraguay',
    title: 'flag for Paraguay',
  },
  {
    code: 'QA',
    emoji: '🇶🇦',
    unicode: 'U+1F1F6 U+1F1E6',
    name: 'Qatar',
    title: 'flag for Qatar',
  },
  {
    code: 'RE',
    emoji: '🇷🇪',
    unicode: 'U+1F1F7 U+1F1EA',
    name: 'Réunion',
    title: 'flag for Réunion',
  },
  {
    code: 'RO',
    emoji: '🇷🇴',
    unicode: 'U+1F1F7 U+1F1F4',
    name: 'Romania',
    title: 'flag for Romania',
  },
  {
    code: 'RS',
    emoji: '🇷🇸',
    unicode: 'U+1F1F7 U+1F1F8',
    name: 'Serbia',
    title: 'flag for Serbia',
  },
  {
    code: 'RU',
    emoji: '🇷🇺',
    unicode: 'U+1F1F7 U+1F1FA',
    name: 'Russia',
    title: 'flag for Russia',
  },
  {
    code: 'RW',
    emoji: '🇷🇼',
    unicode: 'U+1F1F7 U+1F1FC',
    name: 'Rwanda',
    title: 'flag for Rwanda',
  },
  {
    code: 'SA',
    emoji: '🇸🇦',
    unicode: 'U+1F1F8 U+1F1E6',
    name: 'Saudi Arabia',
    title: 'flag for Saudi Arabia',
  },
  {
    code: 'SB',
    emoji: '🇸🇧',
    unicode: 'U+1F1F8 U+1F1E7',
    name: 'Solomon Islands',
    title: 'flag for Solomon Islands',
  },
  {
    code: 'SC',
    emoji: '🇸🇨',
    unicode: 'U+1F1F8 U+1F1E8',
    name: 'Seychelles',
    title: 'flag for Seychelles',
  },
  {
    code: 'SD',
    emoji: '🇸🇩',
    unicode: 'U+1F1F8 U+1F1E9',
    name: 'Sudan',
    title: 'flag for Sudan',
  },
  {
    code: 'SE',
    emoji: '🇸🇪',
    unicode: 'U+1F1F8 U+1F1EA',
    name: 'Sweden',
    title: 'flag for Sweden',
  },
  {
    code: 'SG',
    emoji: '🇸🇬',
    unicode: 'U+1F1F8 U+1F1EC',
    name: 'Singapore',
    title: 'flag for Singapore',
  },
  {
    code: 'SH',
    emoji: '🇸🇭',
    unicode: 'U+1F1F8 U+1F1ED',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    title: 'flag for Saint Helena, Ascension and Tristan Da Cunha',
  },
  {
    code: 'SI',
    emoji: '🇸🇮',
    unicode: 'U+1F1F8 U+1F1EE',
    name: 'Slovenia',
    title: 'flag for Slovenia',
  },
  {
    code: 'SJ',
    emoji: '🇸🇯',
    unicode: 'U+1F1F8 U+1F1EF',
    name: 'Svalbard and Jan Mayen',
    title: 'flag for Svalbard and Jan Mayen',
  },
  {
    code: 'SK',
    emoji: '🇸🇰',
    unicode: 'U+1F1F8 U+1F1F0',
    name: 'Slovakia',
    title: 'flag for Slovakia',
  },
  {
    code: 'SL',
    emoji: '🇸🇱',
    unicode: 'U+1F1F8 U+1F1F1',
    name: 'Sierra Leone',
    title: 'flag for Sierra Leone',
  },
  {
    code: 'SM',
    emoji: '🇸🇲',
    unicode: 'U+1F1F8 U+1F1F2',
    name: 'San Marino',
    title: 'flag for San Marino',
  },
  {
    code: 'SN',
    emoji: '🇸🇳',
    unicode: 'U+1F1F8 U+1F1F3',
    name: 'Senegal',
    title: 'flag for Senegal',
  },
  {
    code: 'SO',
    emoji: '🇸🇴',
    unicode: 'U+1F1F8 U+1F1F4',
    name: 'Somalia',
    title: 'flag for Somalia',
  },
  {
    code: 'SR',
    emoji: '🇸🇷',
    unicode: 'U+1F1F8 U+1F1F7',
    name: 'Suriname',
    title: 'flag for Suriname',
  },
  {
    code: 'SS',
    emoji: '🇸🇸',
    unicode: 'U+1F1F8 U+1F1F8',
    name: 'South Sudan',
    title: 'flag for South Sudan',
  },
  {
    code: 'ST',
    emoji: '🇸🇹',
    unicode: 'U+1F1F8 U+1F1F9',
    name: 'Sao Tome and Principe',
    title: 'flag for Sao Tome and Principe',
  },
  {
    code: 'SV',
    emoji: '🇸🇻',
    unicode: 'U+1F1F8 U+1F1FB',
    name: 'El Salvador',
    title: 'flag for El Salvador',
  },
  {
    code: 'SX',
    emoji: '🇸🇽',
    unicode: 'U+1F1F8 U+1F1FD',
    name: 'Sint Maarten (Dutch Part)',
    title: 'flag for Sint Maarten (Dutch Part)',
  },
  {
    code: 'SY',
    emoji: '🇸🇾',
    unicode: 'U+1F1F8 U+1F1FE',
    name: 'Syrian Arab Republic',
    title: 'flag for Syrian Arab Republic',
  },
  {
    code: 'SZ',
    emoji: '🇸🇿',
    unicode: 'U+1F1F8 U+1F1FF',
    name: 'Swaziland',
    title: 'flag for Swaziland',
  },
  {
    code: 'TC',
    emoji: '🇹🇨',
    unicode: 'U+1F1F9 U+1F1E8',
    name: 'Turks and Caicos Islands',
    title: 'flag for Turks and Caicos Islands',
  },
  {
    code: 'TD',
    emoji: '🇹🇩',
    unicode: 'U+1F1F9 U+1F1E9',
    name: 'Chad',
    title: 'flag for Chad',
  },
  {
    code: 'TF',
    emoji: '🇹🇫',
    unicode: 'U+1F1F9 U+1F1EB',
    name: 'French Southern Territories',
    title: 'flag for French Southern Territories',
  },
  {
    code: 'TG',
    emoji: '🇹🇬',
    unicode: 'U+1F1F9 U+1F1EC',
    name: 'Togo',
    title: 'flag for Togo',
  },
  {
    code: 'TH',
    emoji: '🇹🇭',
    unicode: 'U+1F1F9 U+1F1ED',
    name: 'Thailand',
    title: 'flag for Thailand',
  },
  {
    code: 'TJ',
    emoji: '🇹🇯',
    unicode: 'U+1F1F9 U+1F1EF',
    name: 'Tajikistan',
    title: 'flag for Tajikistan',
  },
  {
    code: 'TK',
    emoji: '🇹🇰',
    unicode: 'U+1F1F9 U+1F1F0',
    name: 'Tokelau',
    title: 'flag for Tokelau',
  },
  {
    code: 'TL',
    emoji: '🇹🇱',
    unicode: 'U+1F1F9 U+1F1F1',
    name: 'Timor-Leste',
    title: 'flag for Timor-Leste',
  },
  {
    code: 'TM',
    emoji: '🇹🇲',
    unicode: 'U+1F1F9 U+1F1F2',
    name: 'Turkmenistan',
    title: 'flag for Turkmenistan',
  },
  {
    code: 'TN',
    emoji: '🇹🇳',
    unicode: 'U+1F1F9 U+1F1F3',
    name: 'Tunisia',
    title: 'flag for Tunisia',
  },
  {
    code: 'TO',
    emoji: '🇹🇴',
    unicode: 'U+1F1F9 U+1F1F4',
    name: 'Tonga',
    title: 'flag for Tonga',
  },
  {
    code: 'TR',
    emoji: '🇹🇷',
    unicode: 'U+1F1F9 U+1F1F7',
    name: 'Turkey',
    title: 'flag for Turkey',
  },
  {
    code: 'TT',
    emoji: '🇹🇹',
    unicode: 'U+1F1F9 U+1F1F9',
    name: 'Trinidad and Tobago',
    title: 'flag for Trinidad and Tobago',
  },
  {
    code: 'TV',
    emoji: '🇹🇻',
    unicode: 'U+1F1F9 U+1F1FB',
    name: 'Tuvalu',
    title: 'flag for Tuvalu',
  },
  {
    code: 'TW',
    emoji: '🇹🇼',
    unicode: 'U+1F1F9 U+1F1FC',
    name: 'Taiwan',
    title: 'flag for Taiwan',
  },
  {
    code: 'TZ',
    emoji: '🇹🇿',
    unicode: 'U+1F1F9 U+1F1FF',
    name: 'Tanzania',
    title: 'flag for Tanzania',
  },
  {
    code: 'UA',
    emoji: '🇺🇦',
    unicode: 'U+1F1FA U+1F1E6',
    name: 'Ukraine',
    title: 'flag for Ukraine',
  },
  {
    code: 'UG',
    emoji: '🇺🇬',
    unicode: 'U+1F1FA U+1F1EC',
    name: 'Uganda',
    title: 'flag for Uganda',
  },
  {
    code: 'UM',
    emoji: '🇺🇲',
    unicode: 'U+1F1FA U+1F1F2',
    name: 'United States Minor Outlying Islands',
    title: 'flag for United States Minor Outlying Islands',
  },
  {
    code: 'US',
    emoji: '🇺🇸',
    unicode: 'U+1F1FA U+1F1F8',
    name: 'United States',
    title: 'flag for United States',
  },
  {
    code: 'UY',
    emoji: '🇺🇾',
    unicode: 'U+1F1FA U+1F1FE',
    name: 'Uruguay',
    title: 'flag for Uruguay',
  },
  {
    code: 'UZ',
    emoji: '🇺🇿',
    unicode: 'U+1F1FA U+1F1FF',
    name: 'Uzbekistan',
    title: 'flag for Uzbekistan',
  },
  {
    code: 'VA',
    emoji: '🇻🇦',
    unicode: 'U+1F1FB U+1F1E6',
    name: 'Vatican City',
    title: 'flag for Vatican City',
  },
  {
    code: 'VC',
    emoji: '🇻🇨',
    unicode: 'U+1F1FB U+1F1E8',
    name: 'Saint Vincent and The Grenadines',
    title: 'flag for Saint Vincent and The Grenadines',
  },
  {
    code: 'VE',
    emoji: '🇻🇪',
    unicode: 'U+1F1FB U+1F1EA',
    name: 'Venezuela',
    title: 'flag for Venezuela',
  },
  {
    code: 'VG',
    emoji: '🇻🇬',
    unicode: 'U+1F1FB U+1F1EC',
    name: 'Virgin Islands, British',
    title: 'flag for Virgin Islands, British',
  },
  {
    code: 'VI',
    emoji: '🇻🇮',
    unicode: 'U+1F1FB U+1F1EE',
    name: 'Virgin Islands, U.S.',
    title: 'flag for Virgin Islands, U.S.',
  },
  {
    code: 'VN',
    emoji: '🇻🇳',
    unicode: 'U+1F1FB U+1F1F3',
    name: 'Viet Nam',
    title: 'flag for Viet Nam',
  },
  {
    code: 'VU',
    emoji: '🇻🇺',
    unicode: 'U+1F1FB U+1F1FA',
    name: 'Vanuatu',
    title: 'flag for Vanuatu',
  },
  {
    code: 'WF',
    emoji: '🇼🇫',
    unicode: 'U+1F1FC U+1F1EB',
    name: 'Wallis and Futuna',
    title: 'flag for Wallis and Futuna',
  },
  {
    code: 'WS',
    emoji: '🇼🇸',
    unicode: 'U+1F1FC U+1F1F8',
    name: 'Samoa',
    title: 'flag for Samoa',
  },
  {
    code: 'YE',
    emoji: '🇾🇪',
    unicode: 'U+1F1FE U+1F1EA',
    name: 'Yemen',
    title: 'flag for Yemen',
  },
  {
    code: 'YT',
    emoji: '🇾🇹',
    unicode: 'U+1F1FE U+1F1F9',
    name: 'Mayotte',
    title: 'flag for Mayotte',
  },
  {
    code: 'ZA',
    emoji: '🇿🇦',
    unicode: 'U+1F1FF U+1F1E6',
    name: 'South Africa',
    title: 'flag for South Africa',
  },
  {
    code: 'ZM',
    emoji: '🇿🇲',
    unicode: 'U+1F1FF U+1F1F2',
    name: 'Zambia',
    title: 'flag for Zambia',
  },
  {
    code: 'ZW',
    emoji: '🇿🇼',
    unicode: 'U+1F1FF U+1F1FC',
    name: 'Zimbabwe',
    title: 'flag for Zimbabwe',
  },
];

const newCountriesList = emojiCodes.filter(emojiItem => countryCodes[emojiItem.code]).map(emojiItem => {
  const { emoji, code } = emojiItem;
  const country = countryCodes[emojiItem.code];
  country.emoji = emoji;
  country.code = code;
  return country;
});

fs.writeFile('./newList.js', JSON.stringify(newCountriesList));
